# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'notification_task' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for notification_task

  target 'notification_task-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'notification_taskTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'notification_task-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
end


